# src/Resources/config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    Bene\DemoBundle\:
        resource: '../../*'
        exclude: '../../{Resources,DependencyInjection,**/*Test.php}'
        public: true   # опционально, для удобства отладки


    # пример параметра из конфига
    Bene\DemoBundle\Controller\HelloController:
        public: true
        arguments:
            $greeting: '%bene_demo.greeting%'